when:
  - event: [pull_request, manual]
  - event: push
    branch: development

variables:
  - &ember_image danlynn/ember-cli:5.12.0-node_20.18

steps:
  install:
    image: *ember_image
    commands:
      - npm ci --no-fund

  lint-js:
    image: *ember_image
    depends_on: [install]
    commands:
      - npm run lint:js
  
  lint-hbs:
    image: *ember_image
    depends_on: [install]
    commands:
      - npm run lint:hbs

  lint-css:
    image: *ember_image
    depends_on: [install]
    commands:
      - npm run lint:css

  dependency-lint:
    image: *ember_image
    depends_on: [install]
    commands:
      - npx ember dependency-lint

  test:
    image: *ember_image
    depends_on: [install]
    commands:
      - npm run test:ember

  build:
    image: *ember_image
    depends_on: [install]
    commands:
      - npx ember build --environment=production --output-path=/tmp/dist
